services:
    backend:
        build: .
        container_name: game-backend
        command: npm run dev
        volumn:
            - .:/app
            - /app/node_modules
        ports:
            - "3030:3030"
        environment:
            DB_HOST: db
            DB_USER: mark
            DB_PASSWORD: mark
            DB_NAME: game_backend
            JWT_SECRET: "my_super_secret_123!@#"
        depends_on:
            - db

    db:
        image: postgres:15
        container_name: game-db
        restart: always
        environment:
            POSTGRES_USER: mark
            POSTGRES_PASSWORD: mark
            POSTGRES_DB: game_backend
        ports:
            - "5433:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
