services:
    backend:
        build: .
        container_name: game-backend
        ports:
            - "3030:3030"
        environment:
            DB_HOST: db
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_NAME: game_backend
            JWT_SECRET: "supersecret"
        depends_on:
            - db

    db:
        image: postgres:15
        container_name: game-db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: game_backend
        ports:
            - "5433:5432"
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
